name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create ZIP archive
        run: |
          zip -r linkedin-comments-scraper-${{ github.ref_name }}.zip ./src

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: linkedin-comments-scraper-${{ github.ref_name }}.zip
